### Search API - invoke from Azure Functions

GET http://localhost:7071/api/search

### Search API - invoke from Static Web Apps

GET http://localhost:4280/api/search

### Embeddings API - invoke from Azure Functions

GET http://localhost:7071/api/embeddings

### Embeddings API - invoke from Static Web Apps

GET http://localhost:4280/api/embeddings

### Brochure API - invoke from Azure Functions
POST http://localhost:7071/api/brochure
Content-Type: application/json

{
    "@search.score": 1,
    "HotelId": "45",
    "HotelName": "Arcadia Resort & Restaurant",
    "Description": "The largest year-round resort in the area offering more of everything for your vacation – at the best value!  What can you enjoy while at the resort, aside from the mile-long sandy beaches of the lake? Check out our activities sure to excite both young and young-at-heart guests. We have it all, including being named “Property of the Year” and a “Top Ten Resort” by top publications.",
    "Description_fr": "La plus grande station de toute l'année dans la région offrant plus de tout pour vos vacances-au meilleur rapport qualité-prix!  Que pouvez-vous profiter de la station, en dehors des kilomètres de longues plages de sable du lac? Découvrez nos activités pour vous exciter à la fois les jeunes et les jeunes-à-coeur invités. Nous avons tout, y compris d'être nommé \"propriété de l'année\" et un \"Top Ten Resort\" par Top publications.",
    "Category": "Suite",
    "Tags": [
    "view",
    "laundry service",
    "view"
    ]
}

### Brochure API - invoke from Static Web Apps
POST http://localhost:4280/api/brochure
Content-Type: application/json

{
    "@search.score": 1,
    "HotelId": "45",
    "HotelName": "Arcadia Resort & Restaurant",
    "Description": "The largest year-round resort in the area offering more of everything for your vacation – at the best value!  What can you enjoy while at the resort, aside from the mile-long sandy beaches of the lake? Check out our activities sure to excite both young and young-at-heart guests. We have it all, including being named “Property of the Year” and a “Top Ten Resort” by top publications.",
    "Description_fr": "La plus grande station de toute l'année dans la région offrant plus de tout pour vos vacances-au meilleur rapport qualité-prix!  Que pouvez-vous profiter de la station, en dehors des kilomètres de longues plages de sable du lac? Découvrez nos activités pour vous exciter à la fois les jeunes et les jeunes-à-coeur invités. Nous avons tout, y compris d'être nommé \"propriété de l'année\" et un \"Top Ten Resort\" par Top publications.",
    "Category": "Suite",
    "Tags": [
    "view",
    "laundry service",
    "view"
    ]
}